### ISSUE TITLE
Sass (indented) support

### ISSUE THREAD

**Issue by RobertSandiford** [zaydek/vscode-sass-template-strings#1]
HI zaydek,

Any idea how to get this to support .sass (indented) synxtax? It's just scss traditional syntax right now.

Happy to work on it with you

**Comment by zaydek** [comment]
Hi Robert, thanks for the interest. It's not something I'm particularly interested in supporting but I can give you a high-level idea of what's probably needed if you're inclined.

In theory you need to modify [`syntaxes/sass-template.json`](https://github.com/zaydek/vscode-sass-template-strings/blob/master/syntaxes/sass-template.json) so that `"include": "source.css.scss"` points to `"source.css.sass"` instead. Note that this assumes VS Code has built-in support for Sass syntax highlighting, not just SCSS.

You should be able to pretty much just clone this repo, change that one line of code and check to see that it works locally. If that works, publishing to the VS Code marketplace is pretty easy too and happens pretty quickly.

If you have any problems just let me know.

**Comment by RobertSandiford** [comment]
Hi zaydek,

Yep I solved it. source.sass is provided I think by the indented sass project.

I can give you the code if you want to publish it - I'm just using it locally.

**Comment by zaydek** [comment]
That's great! I wasn't sure if `sass` would just work. I'm not currently using my own extension right now so I don't feel a great sense of urgency to develop on it, but you're more than welcome to publish your extension to the VS Code marketplace.
